name: Tests

on: push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Setup
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -qq libcurl4-gnutls-dev
    - name: Run Tests
      run: |
        make
        sudo make test

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Setup
      shell: bash
      run: |
        wget https://curl.haxx.se/download/curl-7.69.1.tar.gz
        tar xzf curl-*
        cd curl-*
        ./configure --with-darwinssl
        make
        sudo make install
    - name: Run Tests
      run: |
        make
        sudo make test

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: System Setup
      shell: bash
      run: |
        npx simple-get-bin https://curl.haxx.se/download/curl-7.69.1.tar.gz > curl-7.69.1.tar.gz
        tar xzf curl-7.69.1.tar.gz
        cd curl-7.69.1
        make mingw32
        make install
    - name: Run Tests
      run: |
        make NO_PTHREADS=1 STATIC=true EXE=true
        make test
